// src/components/scenes/castle-walls/CastleWalls.vue
<script setup lang="ts">
const props = defineProps<{
  startVw: number;
  wallTransform: string;
  postTransform: string;
}>();
</script>

<template>
  <div :class="$style.scenario" :style="{ left: `${props.startVw}vw` }" aria-hidden="true" />

  <section
    :class="['zone', $style.profileZone]"
    :style="{ left: `${props.startVw + 100}vw` }"
    aria-labelledby="perfil-title"
  >
    <div :class="[$style.legend, $style.legendOrigin]">
      <small>CAPÍTULO I · EL ORIGEN</small>
      <h2 id="perfil-title">Una leyenda escrita en código</h2>
      <p>En Guadalajara comenzó el viaje de un creador inquieto, guiado por la curiosidad y el deseo de convertir problemas complejos en experiencias claras.</p>
    </div>

    <div :class="[$style.legend, $style.legendCalling]">
      <small>EL LLAMADO</small>
      <h2>Construir, aprender y guiar</h2>
      <p>Durante más de ocho años ha creado productos web y móviles, liderado equipos y compartido conocimiento con nuevas generaciones.</p>
      <blockquote>“Meticuloso, innovador y orientado a resolver problemas.”</blockquote>
    </div>

    <div :class="[$style.raven, $style.ravenDistant]" aria-hidden="true"><i /></div>
    <div :class="$style.wanderer" aria-hidden="true"><i /></div>
    <div :class="$style.castleThreshold"><span>LAS PUERTAS DEL OFICIO</span><b>ENTRAR AL CASTILLO</b></div>
    <div :class="['gate', $style.levelGate]"><b>NIVEL 3</b></div>
  </section>

  <Teleport to="body">
    <div :class="[$style.castleWallTransition, $style.castleWallBack]" :style="{ transform: wallTransform }" aria-hidden="true" />
    <div :class="[$style.castleWallTransition, $style.castleWallFront]" :style="{ transform: wallTransform }" aria-hidden="true" />
    <div :class="$style.foregroundPost" :style="{ transform: postTransform }" aria-hidden="true">
      <div :class="[$style.raven, $style.ravenForeground]"><i /></div>
    </div>
  </Teleport>
</template>

<style module lang="scss" src="./CastleWalls.module.scss"></style>

// app/scenes/castle-walls/CastleWalls.tsx
import styles from "./CastleWalls.module.css";

interface CastleWallsOverlayProps {
  layerTransform: (originVw: number) => string;
  startVw: number;
}

interface CastleWallsPositionProps {
  startVw: number;
}

export function CastleWallsBackground({ startVw }: CastleWallsPositionProps) {
  return <div className={styles.scenario} style={{ left: `${startVw}vw` }} aria-hidden="true" />;
}

export function CastleWallsWorld({ startVw }: CastleWallsPositionProps) {
  return (
    <section
      className={`zone ${styles.profileZone}`}
      style={{ left: `${startVw + 100}vw` }}
      aria-labelledby="perfil-title"
    >
        <div className={`${styles.legend} ${styles.legendOrigin}`}>
          <small>CAPÍTULO I · EL ORIGEN</small>
          <h2 id="perfil-title">Una leyenda escrita en código</h2>
          <p>En Guadalajara comenzó el viaje de un creador inquieto, guiado por la curiosidad y el deseo de convertir problemas complejos en experiencias claras.</p>
        </div>

        <div className={`${styles.legend} ${styles.legendCalling}`}>
          <small>EL LLAMADO</small>
          <h2>Construir, aprender y guiar</h2>
          <p>Durante más de ocho años ha creado productos web y móviles, liderado equipos y compartido conocimiento con nuevas generaciones.</p>
          <blockquote>“Meticuloso, innovador y orientado a resolver problemas.”</blockquote>
        </div>

        <div className={`${styles.raven} ${styles.ravenDistant}`} aria-hidden="true"><i /></div>
        <div className={styles.wanderer} aria-hidden="true"><i /></div>
        <div className={styles.castleThreshold}><span>LAS PUERTAS DEL OFICIO</span><b>ENTRAR AL CASTILLO</b></div>
        <div className={`gate ${styles.levelGate}`}><b>NIVEL 3</b></div>
    </section>
  );
}

export function CastleWallsOverlay({ layerTransform, startVw }: CastleWallsOverlayProps) {
  const wallTransform = { transform: layerTransform(startVw + 260) };

  return (
    <>
      <div className={`${styles.castleWallTransition} ${styles.castleWallBack}`} style={wallTransform} aria-hidden="true" />
      <div className={`${styles.castleWallTransition} ${styles.castleWallFront}`} style={wallTransform} aria-hidden="true" />
      <div className={styles.foregroundPost} style={{ transform: layerTransform(startVw + 72) }} aria-hidden="true">
        <div className={`${styles.raven} ${styles.ravenForeground}`}><i /></div>
      </div>
    </>
  );
}
